models:
  name:
    - glm-4
    

  chat_completion_api: https://open.bigmodel.cn/api/paas/v4/chat/completions
  embedding_api: https://open.bigmodel.cn/api/paas/v4/embeddings
  # embedding_api: http://10.241.132.208:28000/v1/embeddings
  # chat_completion_api: http://10.241.132.208:28000/v1/chat/completions
  # openai_embedding_api: https://api.openai.com/v1/embeddings
  # openai_chat_completion_api: https://api.openai.com/v1/chat/completions
